import { useState } from "react";
import type { Recommendation } from "../types";
import { Lightbulb, ArrowRight, Check, Loader2 } from "lucide-react";

interface Props {
  recommendations: Recommendation[];
  onRefresh?: () => void;
}

const CONFIDENCE_CONFIG: Record<string, { badge: string; shadow: string }> = {
  high: { badge: "bg-emerald-500/10 text-emerald-400 border-emerald-500/30", shadow: "shadow-[0_0_10px_rgba(16,185,129,0.2)]" },
  medium: { badge: "bg-amber-500/10 text-amber-400 border-amber-500/30", shadow: "shadow-[0_0_10px_rgba(245,158,11,0.2)]" },
  low: { badge: "bg-slate-500/10 text-slate-400 border-white/10", shadow: "" },
};

const TYPE_LABELS: Record<string, string> = {
  rightsize: "Right-size compute",
  stop_idle: "Halt idle instances",
  delete_unused: "Purge unattached volumes",
  change_tier: "Change storage tier",
};

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:4000";

export function Recommendations({ recommendations, onRefresh }: Props) {
  const [appliedIds, setAppliedIds] = useState<Set<string>>(new Set());
  const [loadingIds, setLoadingIds] = useState<Set<string>>(new Set());

  if (recommendations.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-slate-500">
        <Lightbulb className="w-12 h-12 mb-3 opacity-30 text-amber-400 animate-pulse" />
        <p className="text-sm font-medium text-white/80">Everything is fully optimized</p>
        <p className="text-[11px] mt-1 text-slate-500">No new recommendations generated by the AI engine.</p>
      </div>
    );
  }

  const totalSavings = recommendations.reduce((s, r) => s + r.estimated_monthly_savings, 0);

  async function applyRecommendation(rec: Recommendation) {
    if (appliedIds.has(rec.id) || loadingIds.has(rec.id)) return;

    setLoadingIds((prev) => new Set(prev).add(rec.id));

    try {
      // Use the simulate-scenario endpoint to apply the recommendation
      const scenario = rec.type === "stop_idle" ? "stop" : rec.type === "rightsize" ? "downsize" : "stop";

      const response = await fetch(`${API_BASE}/api/analytics/simulate-scenario`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          resourceId: rec.resource_id,
          scenario,
        }),
      });

      if (!response.ok) throw new Error("Failed to apply");

      // If it's a stop action, also trigger the actual stop via action approval flow
      if (rec.type === "stop_idle" || rec.type === "delete_unused") {
        // Directly trigger a pipeline scan which picks up the recommendation
        await fetch(`${API_BASE}/api/dashboard/trigger-scan`, { method: "POST" });
      }

      setAppliedIds((prev) => new Set(prev).add(rec.id));

      // Refresh data after a short delay
      if (onRefresh) {
        setTimeout(onRefresh, 2000);
      }
    } catch (err) {
      console.error("Failed to apply recommendation:", err);
    } finally {
      setLoadingIds((prev) => {
        const next = new Set(prev);
        next.delete(rec.id);
        return next;
      });
    }
  }

  return (
    <div className="flex flex-col h-full gap-4">
      <div className="flex items-center justify-between px-2 bg-emerald-500/5 border border-emerald-500/20 py-3 rounded-xl mb-2">
        <div className="flex items-center gap-2">
          <Lightbulb className="w-5 h-5 text-emerald-400" />
          <span className="text-xs font-bold uppercase tracking-widest text-emerald-300">
            {recommendations.length} Optimization{recommendations.length !== 1 ? "s" : ""} Available
          </span>
        </div>
        <span className="text-lg font-black text-emerald-400 drop-shadow-[0_0_8px_rgba(52,211,153,0.5)]">
          -${totalSavings.toFixed(2)}<span className="text-[10px] text-emerald-500 font-normal uppercase">/mo potential</span>
        </span>
      </div>

      <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 auto-rows-max">
        {recommendations.map((r) => {
          const conf = CONFIDENCE_CONFIG[r.confidence] || CONFIDENCE_CONFIG.low;
          const isApplied = appliedIds.has(r.id);
          const isLoading = loadingIds.has(r.id);

          return (
            <div key={r.id} className="p-4 rounded-xl bg-black/40 border border-white/5 hover:border-white/20 transition-all duration-300 animate-slide-in-up flex flex-col group h-full">
              <div className="flex items-start justify-between gap-2 mb-3">
                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border ${conf.badge} ${conf.shadow}`}>
                  {r.confidence} Conf.
                </span>
                <span className="text-sm font-black text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded shrink-0">
                  -${r.estimated_monthly_savings.toFixed(2)}<span className="text-[9px] text-emerald-500 font-medium">/mo</span>
                </span>
              </div>
              
              <div className="mb-2">
                <span className="text-sm font-bold text-white block mb-1">
                  {TYPE_LABELS[r.type] || r.type.replace(/_/g, " ")}
                </span>
                <span className="font-mono text-[10px] text-slate-400 bg-white/5 px-1.5 py-0.5 rounded border border-white/5 block w-fit truncate max-w-full">
                  {(r.resource_name || r.resource_id).split("/").pop()}
                </span>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed mb-4 flex-1">"{r.reason}"</p>

              <div className="flex items-center gap-2 text-[11px] font-mono bg-black/60 p-2 rounded-lg border border-white/5 mt-auto">
                <span className="text-red-400 max-w-[40%] truncate">{r.current_config}</span>
                <ArrowRight className="w-3 h-3 text-slate-500 shrink-0" />
                <span className="text-emerald-400 max-w-[45%] truncate font-bold">{r.recommended_config}</span>
              </div>
              
              <button
                onClick={() => applyRecommendation(r)}
                disabled={isApplied || isLoading}
                className={`mt-3 w-full py-2 rounded-lg text-xs font-bold uppercase tracking-widest transition-all cursor-pointer flex items-center justify-center gap-2 ${
                  isApplied
                    ? "bg-emerald-600/20 text-emerald-400 border border-emerald-500/30"
                    : isLoading
                    ? "bg-indigo-600/20 text-indigo-300 border border-indigo-500/30 opacity-80"
                    : "bg-indigo-600/20 hover:bg-indigo-600 border border-indigo-500/30 hover:border-indigo-500 text-indigo-300 hover:text-white opacity-0 group-hover:opacity-100"
                }`}
              >
                {isApplied ? (
                  <><Check className="w-3.5 h-3.5" /> Applied</>
                ) : isLoading ? (
                  <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Applying...</>
                ) : (
                  "Apply Update"
                )}
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}
