import type { ResourceInfo } from "../collectors/resource-inventory";

export const SIMULATED_RESOURCES: ResourceInfo[] = [
  {
    resourceId: "4839201748291056",
    resourceType: "compute",
    name: "prod-api-server",
    status: "RUNNING",
    hourlyCost: 0.03351,
    metadata: { machineType: "e2-medium", zone: "us-central1-a", labels: { env: "production" } },
  },
  {
    resourceId: "7291038475610293",
    resourceType: "compute",
    name: "staging-worker",
    status: "RUNNING",
    hourlyCost: 0.00838,
    metadata: { machineType: "e2-micro", zone: "us-central1-a", labels: { env: "staging" } },
  },
  {
    resourceId: "1056384729103847",
    resourceType: "compute",
    name: "dev-sandbox",
    status: "RUNNING",
    hourlyCost: 0.0076,
    metadata: { machineType: "f1-micro", zone: "us-central1-b", labels: {} },
  },
  {
    resourceId: "process-uploads",
    resourceType: "cloud_function",
    name: "process-uploads",
    status: "active",
    hourlyCost: 0,
    metadata: { runtime: "nodejs18", maxInstanceCount: 1000, availableMemory: "256Mi", fullName: "projects/demo/locations/us-central1/functions/process-uploads" },
  },
  {
    resourceId: "send-notifications",
    resourceType: "cloud_function",
    name: "send-notifications",
    status: "active",
    hourlyCost: 0,
    metadata: { runtime: "nodejs18", maxInstanceCount: 100, availableMemory: "128Mi", fullName: "projects/demo/locations/us-central1/functions/send-notifications" },
  },
  {
    resourceId: "8374019283746501",
    resourceType: "disk",
    name: "old-backup-disk",
    status: "unattached",
    hourlyCost: 0.00055,
    metadata: { sizeGb: 10, diskType: "pd-standard", zone: "us-central1-a" },
  },
  {
    resourceId: "2918374650182937",
    resourceType: "disk",
    name: "prod-api-boot",
    status: "attached",
    hourlyCost: 0.00233,
    metadata: { sizeGb: 10, diskType: "pd-ssd", zone: "us-central1-a", users: ["4839201748291056"] },
  },
  {
    resourceId: "cloudsnip-assets-prod",
    resourceType: "gcs",
    name: "cloudsnip-assets-prod",
    status: "active",
    hourlyCost: 0,
    metadata: { location: "US-CENTRAL1", storageClass: "STANDARD" },
  },
  {
    resourceId: "cloudsnip-logs-archive",
    resourceType: "gcs",
    name: "cloudsnip-logs-archive",
    status: "active",
    hourlyCost: 0,
    metadata: { location: "US", storageClass: "NEARLINE" },
  },
];
